sonar.projectKey=eiaiproject_Ledjer
sonar.organization=eiaiproject
sonar.host.url=https://sonarcloud.io

sonar.sources=apps/web/src,apps/web/worker
sonar.tests=apps/web/src,apps/web/worker
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/.wrangler/**,**/scripts/**,**/*.config.ts,**/*.config.js,**/*.config.json,**/_headers,**/postbuild-*"
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/.wrangler/**

sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.ts.tslint.reportPaths=apps/web/eslint-report.json
sonar.eslint.reportPaths=apps/web/eslint-report.json

sonar.sourceEncoding=UTF-8
