#!/usr/bin/env bash
# Seed the local (miniflare) D1 database with the E2E fixture user + org.
# Idempotent — safe to run after every fresh `wrangler d1 migrations apply --local`.
# The E2E suite (playwright local-full mode) logs in as ledjer@yopmail.com
# and asserts on the org 046e96ee-6399-4704-ad25-66bc7f917742.
#
# This script seeds:
#   1. User + org + owner membership
#   2. Default chart of accounts (mirror of DEFAULT_ACCOUNTS in organization.service.ts)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DB_DIR="$ROOT/apps/web/.wrangler/state/v3/d1/miniflare-D1DatabaseObject"
DB="$(find "$DB_DIR" -maxdepth 1 -name '*.sqlite' ! -name 'metadata.sqlite' 2>/dev/null | head -1)"

if [[ -z "$DB" ]]; then
  echo "[seed-e2e-local] WARN: no local D1 database found (run db:migrations:apply:local first)" >&2
  exit 0
fi

EMAIL='ledjer@yopmail.com'
PASSWORD='Ledjer26#'
USER_ID='91175ffd-dea8-4e5e-9c83-7e2f5b6a4c21'
ORG_ID='046e96ee-6399-4704-ad25-66bc7f917742'

# Generate SQL via node (accounts + password hash) — keeps bash simple.
SQL_FILE="$(mktemp /tmp/seed-e2e-local.XXXXXX)"
node - "$EMAIL" "$PASSWORD" "$USER_ID" "$ORG_ID" > "$SQL_FILE" <<'NODE'
const crypto = require("node:crypto");
const [,, email, password, userId, orgId] = process.argv;
const now = Date.now();

// ── Password hash ───────────────────────────────────────────────
const salt = crypto.randomBytes(16);
const material = Buffer.from(`${password}\u0000`, "utf8");
const key = crypto.pbkdf2Sync(material, salt, 100_000, 32, "sha256");
const hash = `pbkdf2-sha256$100000$${salt.toString("base64")}$${key.toString("base64")}`;

// ── Account UUIDs (14 MVP default accounts) ─────────────────────
// Mirror of DEFAULT_ACCOUNTS in worker/services/organization.service.ts.
const accounts = [
  { code: "1110", name: "Kas",                    accountClass: "asset",   accountSubtype: "cash" },
  { code: "1120", name: "Bank",                   accountClass: "asset",   accountSubtype: "bank" },
  { code: "3110", name: "Modal Pemilik",          accountClass: "equity",  accountSubtype: null },
  { code: "3120", name: "Pengambilan Pemilik",    accountClass: "equity",  accountSubtype: null },
  { code: "4110", name: "Pendapatan Usaha",       accountClass: "income",  accountSubtype: null },
  { code: "4120", name: "Pendapatan Lain",        accountClass: "income",  accountSubtype: null },
  { code: "6110", name: "Beban Gaji & Upah",      accountClass: "expense", accountSubtype: null },
  { code: "6120", name: "Beban Sewa",             accountClass: "expense", accountSubtype: null },
  { code: "6130", name: "Beban Pemasaran",        accountClass: "expense", accountSubtype: null },
  { code: "6140", name: "Beban Transportasi",     accountClass: "expense", accountSubtype: null },
  { code: "6150", name: "Beban Komunikasi & Internet", accountClass: "expense", accountSubtype: null },
  { code: "6160", name: "Beban Perlengkapan",     accountClass: "expense", accountSubtype: null },
  { code: "6170", name: "Beban Administrasi",     accountClass: "expense", accountSubtype: null },
  { code: "6180", name: "Beban Lain-lain",        accountClass: "expense", accountSubtype: null },
];

const accountLines = accounts.map(a => {
  const id = crypto.randomUUID();
  const subtype = a.accountSubtype ? `'${a.accountSubtype}'` : "NULL";
  return `INSERT OR IGNORE INTO accounts
  (id, organization_id, code, name, account_class, account_subtype, is_system, is_active, created_at, updated_at)
VALUES ('${id}', '${orgId}', '${a.code}', '${a.name}', '${a.accountClass}', ${subtype}, 1, 1, ${now}, ${now});`;
}).join("\n");

process.stdout.write(`-- Generated by scripts/seed-e2e-local.sh
-- PBKDF2-SHA256 hash for password: ${password}

-- 1. User
INSERT OR IGNORE INTO users (id, email, password_hash, full_name, status, created_at, updated_at)
VALUES ('${userId}', '${email}', '${hash}', 'Ledjer E2E', 'active', ${now}, ${now});

-- 2. Organization
INSERT OR IGNORE INTO organizations (id, name, base_currency, status, created_at, updated_at)
VALUES ('${orgId}', 'Ledjer E2E Test', 'IDR', 'active', ${now}, ${now});

-- 3. Owner membership
INSERT OR IGNORE INTO memberships (id, organization_id, user_id, role, created_at)
VALUES ('seed-owner', '${orgId}', '${userId}', 'owner', ${now});

-- 4. Default chart of accounts (required for transaction E2E tests)
${accountLines}
`);
NODE

# Apply via sqlite3
sqlite3 "$DB" < "$SQL_FILE"
rm -f "$SQL_FILE"

echo "[seed-e2e-local] seeded $EMAIL -> $ORG_ID (accounts included)"