// Mirrors apps/web/worker/db/schema.ts - kept in sync manually. The admin
// worker backs up the same tables as the main worker so manifests match.
export const CORE_TABLES = [
  "users",
  "sessions",
  "email_verifications",
  "password_reset_tokens",
  "login_attempts",
  "oauth_accounts",
  "organizations",
  "organization_members",
  "organization_invitations",
  "accounts",
  "parties",
  "products",
  "transactions",
  "transaction_lines",
  "journal_entries",
  "journal_lines",
  "stock_movements",
  "period_locks",
  "organization_document_counters",
  "audit_logs",
  "attachments",
  "bank_statements",
  "bank_statement_lines",
  "reconciliation_matches",
  "invoices",
  "invoice_lines",
  "payment_allocations",
  "admin_users",
  "admin_sessions",
] as const;
