-- ============================================================================
-- Migration 0028: Remove business_documents and recurring_transactions tables
--
-- Business Documents and Recurring Transactions modules have been removed
-- from the product (PHASES 3-5). This migration safely drops the orphaned
-- database tables.
--
-- SAFETY:
--   - financial transactions generated by recurring schedules are preserved
--     (they are in the transactions/journal_entries/journal_lines tables)
--   - invoices created from document conversion remain independent
--   - child tables are dropped before parent tables (FK order)
--   - organization_document_counters is PRESERVED (still used by invoices
--     and transactions for counter generation)
-- ============================================================================

PRAGMA foreign_keys = ON;

-- ── Drop child tables first (FK dependencies) ─────────────────────────────

-- document_lines depends on business_documents (FK: document_id)
DROP TABLE IF EXISTS document_lines;

-- recurring_execution_log depends on recurring_transactions (FK: recurring_transaction_id)
DROP TABLE IF EXISTS recurring_execution_log;

-- ── Drop parent tables ────────────────────────────────────────────────────

DROP TABLE IF EXISTS business_documents;

DROP TABLE IF EXISTS recurring_transactions;

-- ── Remove indexes associated with dropped tables ─────────────────────────
-- These are cleaned up automatically by SQLite when the tables are dropped.

UPDATE app_metadata SET value = '28' WHERE key = 'schema.foundation';
